### PR TITLE
Add support for Iframes in CMSPage

### PR DESCRIPTION
**Pull request by xkmato**
Add support for Iframe on CMS page. 

May not be the safest option but luckily only admins can access that part of the site. Requirement need is urgent

### CODE REVIEW

**Comment by xkmato** [comment]
@ewheeler Whenever you get time, please.

**Comment by kaleemcf** [comment]
@ewheeler you first commit

**Comment by ewheeler** [comment]
@xkmato nice comment: ```Extremely unsafe: Fix it ASAP```

**Comment by kaleemcf** [comment]
thx bros!

**Pull request merged**
